# Generated by Django 5.2.8 on 2026-01-17 09:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full country name', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('phone_code', models.CharField(help_text='International dialing code (e.g., +1, +91)', max_length=5, validators=[django.core.validators.RegexValidator(message='Phone code must start with + followed by 1-4 digits', regex='^\\+\\d{1,4}$')])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this country available for shipping?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/Province name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='State/Province code', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this state available for shipping?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='user_address.country')),
            ],
            options={
                'verbose_name': 'State/Province',
                'verbose_name_plural': 'States/Provinces',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this city available for delivery?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(help_text='State this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='user_address.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address'), ('both', 'Shipping & Billing Address')], default='both', help_text='Type of address', max_length=10)),
                ('full_name', models.CharField(help_text="Recipient's full name", max_length=200)),
                ('phone', models.CharField(help_text='Contact phone number with country code (e.g., +919876543210)', max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate contact number (optional)', max_length=20, null=True)),
                ('address_line1', models.CharField(help_text='House/Flat number, Building name, Street', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Area, Colony, Sector (optional)', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for easier delivery (optional)', max_length=100, null=True)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP/Postal code', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('verification_status', models.CharField(choices=[('unverified', 'Not Verified'), ('pending', 'Verification Pending'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='unverified', help_text='Address verification status', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date when address was last verified', null=True)),
                ('is_default_shipping', models.BooleanField(default=False, help_text='Is this the default shipping address?')),
                ('is_default_billing', models.BooleanField(default=False, help_text='Is this the default billing address?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this address currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_ref', models.ForeignKey(blank=True, help_text='Reference to standardized city (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='user_address.city')),
                ('country', models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='user_address.country')),
                ('state', models.ForeignKey(help_text='State/Province', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='user_address.state')),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country', 'name'], name='user_addres_country_90c088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state', 'name'], name='user_addres_state_i_e1aebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_active'], name='user_addres_user_id_bfbe9f_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default_shipping'], name='user_addres_user_id_e85f98_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default_billing'], name='user_addres_user_id_c46dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'address_type'], name='user_addres_user_id_234777_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['country', 'state', 'city'], name='user_addres_country_6df3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['postal_code'], name='user_addres_postal__e4c9af_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['verification_status'], name='user_addres_verific_f651de_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['latitude', 'longitude'], name='user_addres_latitud_0ea38a_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('address_type__in', ['shipping', 'both']), ('is_active', True), ('is_default_shipping', True)), fields=('user', 'address_type'), name='unique_default_shipping_per_user_type'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('address_type__in', ['billing', 'both']), ('is_active', True), ('is_default_billing', True)), fields=('user', 'address_type'), name='unique_default_billing_per_user_type'),
        ),
    ]
