# Generated by Django 5.2.8 on 2025-12-16 06:29

import cloudinary.models
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-is_featured', '-priority', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_br_slug_d4d839_idx'), models.Index(fields=['is_active'], name='products_br_is_acti_297ee1_idx'), models.Index(fields=['is_featured', 'priority'], name='products_br_is_feat_8d162b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name', max_length=250)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon Class')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(blank=True, db_index=True, editable=False, max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'), models.Index(fields=['path'], name='products_ca_path_e3cf32_idx'), models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'), models.Index(fields=['show_in_menu'], name='products_ca_show_in_7b6386_idx'), models.Index(fields=['is_active', 'sort_order'], name='products_ca_is_acti_5dffbf_idx'), models.Index(fields=['tree_id', 'lft'], name='products_category_tree_id_0983')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'), models.UniqueConstraint(fields=('path',), name='unique_category_path')],
            },
        ),
    ]
