# Generated by Django 5.2.8 on 2025-12-04 09:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-is_featured', '-priority', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='brand',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g., 1903 for Ford', null=True, verbose_name='Founded Year'),
        ),
        migrations.AddField(
            model_name='brand',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher = appears first in featured sections', verbose_name='Display Priority'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full URL path: electronics/mobile/android', max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from navigation (still accessible via URL)', verbose_name='Show in Main Menu'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome 6 class, e.g., 'fas fa-mobile-alt', 'fas fa-tshirt'", max_length=100, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name. Used in URLs.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='products_br_is_acti_297ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_featured', 'priority'], name='products_br_is_feat_8d162b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='products_ca_path_e3cf32_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_menu'], name='products_ca_show_in_7b6386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'sort_order'], name='products_ca_is_acti_5dffbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_name_per_parent'),
        ),
    ]
